[workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]

[dependencies]
ruff = ">=0.15.0,<0.16"
pyrefly = ">=0.52.0,<0.53"
altair = ">=6.0.0,<7"
pysam = ">=0.23.3,<0.24"
streamlit = ">=1.54.0,<2"
